config/routes.rb
Lab5::Application.routes.draw do
  resources :inventories

  resources :products

end

app/models/inventory.rb
class Inventory < ActiveRecord::Base
	
	has_many :products

end

app/models/product.rb
class Product < ActiveRecord::Base

	belongs_to :inventorys

	validates_presence_of  :title, :descripcion, :price, :image_url,:message => "Falta el ingreso de algun campo"
	validates_numericality_of :price,:message => "El precio debe ser un numero"
	validates_numericality_of :price, :greater_than => 0.1, :message => "El precio debe ser mayor que 0.01"
	validates_uniqueness_of :title, :message => "El titulo debe de ser unico"
	validates_format_of :image_url, :with => /\A((?:[-a-z0-9]+\.)+[gif|jpg|png]{3,})\Z/i ,:message  => "Formato no valido"
	validates_numericality_of :projection, :greater_than => 0,:message => "Proyection > 0"


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  # GET /inventories
  # GET /inventories.xml
  def index
    @inventories = Inventory.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @inventories }
    end
  end

  # GET /inventories/1
  # GET /inventories/1.xml
  def show
    @inventory = Inventory.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @inventory }
    end
  end

  # GET /inventories/new
  # GET /inventories/new.xml
  def new
    @inventory = Inventory.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @inventory }
    end
  end

  # GET /inventories/1/edit
  def edit
    @inventory = Inventory.find(params[:id])
  end

  # POST /inventories
  # POST /inventories.xml
  def create
    @inventory = Inventory.new(params[:inventory])

    respond_to do |format|
      if @inventory.save
        format.html { redirect_to(@inventory, :notice => 'Inventory was successfully created.') }
        format.xml  { render :xml => @inventory, :status => :created, :location => @inventory }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @inventory.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /inventories/1
  # PUT /inventories/1.xml
  def update
    @inventory = Inventory.find(params[:id])

    respond_to do |format|
      if @inventory.update_attributes(params[:inventory])
        format.html { redirect_to(@inventory, :notice => 'Inventory was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @inventory.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /inventories/1
  # DELETE /inventories/1.xml
  def destroy
    @inventory = Inventory.find(params[:id])
    @inventory.destroy

    respond_to do |format|
      format.html { redirect_to(inventories_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.xml
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @products }
    end
  end

  # GET /products/1
  # GET /products/1.xml
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @product }
    end
  end

  # GET /products/new
  # GET /products/new.xml
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.xml
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to(@product, :notice => 'Product was successfully created.') }
        format.xml  { render :xml => @product, :status => :created, :location => @product }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @product.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.xml
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to(@product, :notice => 'Product was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @product.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.xml
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to(products_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/inventories/_form.html.erb
<%= form_for(@inventory) do |f| %>
  <% if @inventory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@inventory.errors.count, "error") %> prohibited this inventory from being saved:</h2>

      <ul>
      <% @inventory.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.text_field :id %>
  </div>
  <div class="field">
    <%= f.label :product_id %><br />
    <%= f.text_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :previous_balance %><br />
    <%= f.text_field :previous_balance %>
  </div>
  <div class="field">
    <%= f.label :new_balance %><br />
    <%= f.text_field :new_balance %>
  </div>
  <div class="field">
    <%= f.label :future_balance %><br />
    <%= f.text_field :future_balance %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/inventories/edit.html.erb
<h1>Editing inventory</h1>

<%= render 'form' %>

<%= link_to 'Show', @inventory %> |
<%= link_to 'Back', inventories_path %>

app/views/inventories/index.html.erb
<h1>Listing inventories</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Product</th>
    <th>Previous balance</th>
    <th>New balance</th>
    <th>Future balance</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @inventories.each do |inventory| %>
  <tr>
    <td><%= inventory.id %></td>
    <td><%= inventory.product_id %></td>
    <td><%= inventory.previous_balance %></td>
    <td><%= inventory.new_balance %></td>
    <td><%= inventory.future_balance %></td>
    <td><%= link_to 'Show', inventory %></td>
    <td><%= link_to 'Edit', edit_inventory_path(inventory) %></td>
    <td><%= link_to 'Destroy', inventory, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Inventory', new_inventory_path %>

app/views/inventories/new.html.erb
<h1>New inventory</h1>

<%= render 'form' %>

<%= link_to 'Back', inventories_path %>

app/views/inventories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @inventory.id %>
</p>

<p>
  <b>Product:</b>
  <%= @inventory.product_id %>
</p>

<p>
  <b>Previous balance:</b>
  <%= @inventory.previous_balance %>
</p>

<p>
  <b>New balance:</b>
  <%= @inventory.new_balance %>
</p>

<p>
  <b>Future balance:</b>
  <%= @inventory.future_balance %>
</p>


<%= link_to 'Edit', edit_inventory_path(@inventory) %> |
<%= link_to 'Back', inventories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lab5</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.text_field :id %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br />
    <%= f.text_area :descripcion %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br />
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :projection %><br />
    <%= f.text_field :projection %>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.text_field :amount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing products</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Title</th>
    <th>Descripcion</th>
    <th>Image url</th>
    <th>Price</th>
    <th>Projection</th>
    <th>Amount</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @products.each do |product| %>
  <tr>
    <td><%= product.id %></td>
    <td><%= product.title %></td>
    <td><%= product.descripcion %></td>
    <td><%= product.image_url %></td>
    <td><%= product.price %></td>
    <td><%= product.projection %></td>
    <td><%= product.amount %></td>
    <td><%= link_to 'Show', product %></td>
    <td><%= link_to 'Edit', edit_product_path(product) %></td>
    <td><%= link_to 'Destroy', product, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @product.id %>
</p>

<p>
  <b>Title:</b>
  <%= @product.title %>
</p>

<p>
  <b>Descripcion:</b>
  <%= @product.descripcion %>
</p>

<p>
  <b>Image url:</b>
  <%= @product.image_url %>
</p>

<p>
  <b>Price:</b>
  <%= @product.price %>
</p>

<p>
  <b>Projection:</b>
  <%= @product.projection %>
</p>

<p>
  <b>Amount:</b>
  <%= @product.amount %>
</p>


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>